/**
 * Liste complète de tous les pays du monde (250+)
 * Triés alphabétiquement en français
 * Usage : import { PAYS_LIST } from '@/lib/countries'
 */

export const PAYS_LIST = [
  { code: "AF", nom: "Afghanistan" },
  { code: "ZA", nom: "Afrique du Sud" },
  { code: "AX", nom: "Åland (Îles)" },
  { code: "AL", nom: "Albanie" },
  { code: "DZ", nom: "Algérie" },
  { code: "DE", nom: "Allemagne" },
  { code: "AD", nom: "Andorre" },
  { code: "AO", nom: "Angola" },
  { code: "AI", nom: "Anguilla" },
  { code: "AQ", nom: "Antarctique" },
  { code: "AG", nom: "Antigua-et-Barbuda" },
  { code: "AN", nom: "Antilles néerlandaises" },
  { code: "SA", nom: "Arabie saoudite" },
  { code: "AR", nom: "Argentine" },
  { code: "AM", nom: "Arménie" },
  { code: "AW", nom: "Aruba" },
  { code: "AU", nom: "Australie" },
  { code: "AT", nom: "Autriche" },
  { code: "AZ", nom: "Azerbaïdjan" },
  { code: "BS", nom: "Bahamas" },
  { code: "BH", nom: "Bahreïn" },
  { code: "BD", nom: "Bangladesh" },
  { code: "BB", nom: "Barbade" },
  { code: "BE", nom: "Belgique" },
  { code: "BZ", nom: "Belize" },
  { code: "BJ", nom: "Bénin" },
  { code: "BM", nom: "Bermudes" },
  { code: "BT", nom: "Bhoutan" },
  { code: "BY", nom: "Biélorussie" },
  { code: "MM", nom: "Birmanie (Myanmar)" },
  { code: "BO", nom: "Bolivie" },
  { code: "BA", nom: "Bosnie-Herzégovine" },
  { code: "BW", nom: "Botswana" },
  { code: "BR", nom: "Brésil" },
  { code: "BN", nom: "Brunéi" },
  { code: "BG", nom: "Bulgarie" },
  { code: "BF", nom: "Burkina Faso" },
  { code: "BI", nom: "Burundi" },
  { code: "CV", nom: "Cabo Verde" },
  { code: "KH", nom: "Cambodge" },
  { code: "CM", nom: "Cameroun" },
  { code: "CA", nom: "Canada" },
  { code: "CF", nom: "Centrafrique" },
  { code: "CL", nom: "Chili" },
  { code: "CN", nom: "Chine" },
  { code: "CX", nom: "Christmas (Île)" },
  { code: "CY", nom: "Chypre" },
  { code: "CC", nom: "Cocos (Îles Keeling)" },
  { code: "CO", nom: "Colombie" },
  { code: "KM", nom: "Comores" },
  { code: "CG", nom: "Congo" },
  { code: "CD", nom: "Congo (RDC)" },
  { code: "CK", nom: "Cook (Îles)" },
  { code: "KP", nom: "Corée du Nord" },
  { code: "KR", nom: "Corée du Sud" },
  { code: "CR", nom: "Costa Rica" },
  { code: "CI", nom: "Côte d'Ivoire" },
  { code: "HR", nom: "Croatie" },
  { code: "CU", nom: "Cuba" },
  { code: "CW", nom: "Curaçao" },
  { code: "DK", nom: "Danemark" },
  { code: "DJ", nom: "Djibouti" },
  { code: "DM", nom: "Dominique" },
  { code: "EG", nom: "Égypte" },
  { code: "AE", nom: "Émirats arabes unis" },
  { code: "EC", nom: "Équateur" },
  { code: "ER", nom: "Érythrée" },
  { code: "ES", nom: "Espagne" },
  { code: "EE", nom: "Estonie" },
  { code: "SZ", nom: "Eswatini" },
  { code: "ET", nom: "Éthiopie" },
  { code: "FK", nom: "Falkland (Îles)" },
  { code: "FO", nom: "Féroé (Îles)" },
  { code: "FJ", nom: "Fidji" },
  { code: "FI", nom: "Finlande" },
  { code: "FR", nom: "France" },
  { code: "GA", nom: "Gabon" },
  { code: "GM", nom: "Gambie" },
  { code: "GE", nom: "Géorgie" },
  { code: "GS", nom: "Géorgie du Sud et Sandwich du Sud" },
  { code: "GH", nom: "Ghana" },
  { code: "GI", nom: "Gibraltar" },
  { code: "GR", nom: "Grèce" },
  { code: "GD", nom: "Grenade" },
  { code: "GL", nom: "Groenland" },
  { code: "GP", nom: "Guadeloupe" },
  { code: "GU", nom: "Guam" },
  { code: "GT", nom: "Guatemala" },
  { code: "GG", nom: "Guernesey" },
  { code: "GN", nom: "Guinée" },
  { code: "GW", nom: "Guinée-Bissau" },
  { code: "GQ", nom: "Guinée équatoriale" },
  { code: "GY", nom: "Guyana" },
  { code: "GF", nom: "Guyane française" },
  { code: "HT", nom: "Haïti" },
  { code: "HM", nom: "Heard et McDonald (Îles)" },
  { code: "HN", nom: "Honduras" },
  { code: "HK", nom: "Hong Kong" },
  { code: "HU", nom: "Hongrie" },
  { code: "IN", nom: "Inde" },
  { code: "ID", nom: "Indonésie" },
  { code: "IQ", nom: "Irak" },
  { code: "IR", nom: "Iran" },
  { code: "IE", nom: "Irlande" },
  { code: "IS", nom: "Islande" },
  { code: "IL", nom: "Israël" },
  { code: "IT", nom: "Italie" },
  { code: "JM", nom: "Jamaïque" },
  { code: "JP", nom: "Japon" },
  { code: "JE", nom: "Jersey" },
  { code: "JO", nom: "Jordanie" },
  { code: "KZ", nom: "Kazakhstan" },
  { code: "KE", nom: "Kenya" },
  { code: "KG", nom: "Kirghizistan" },
  { code: "KI", nom: "Kiribati" },
  { code: "XK", nom: "Kosovo" },
  { code: "KW", nom: "Koweït" },
  { code: "LA", nom: "Laos" },
  { code: "LS", nom: "Lesotho" },
  { code: "LV", nom: "Lettonie" },
  { code: "LB", nom: "Liban" },
  { code: "LR", nom: "Libéria" },
  { code: "LY", nom: "Libye" },
  { code: "LI", nom: "Liechtenstein" },
  { code: "LT", nom: "Lituanie" },
  { code: "LU", nom: "Luxembourg" },
  { code: "MO", nom: "Macao" },
  { code: "MK", nom: "Macédoine du Nord" },
  { code: "MG", nom: "Madagascar" },
  { code: "MY", nom: "Malaisie" },
  { code: "MW", nom: "Malawi" },
  { code: "MV", nom: "Maldives" },
  { code: "ML", nom: "Mali" },
  { code: "MT", nom: "Malte" },
  { code: "IM", nom: "Man (Île de)" },
  { code: "MA", nom: "Maroc" },
  { code: "MH", nom: "Marshall (Îles)" },
  { code: "MQ", nom: "Martinique" },
  { code: "MU", nom: "Maurice" },
  { code: "MR", nom: "Mauritanie" },
  { code: "YT", nom: "Mayotte" },
  { code: "MX", nom: "Mexique" },
  { code: "FM", nom: "Micronésie" },
  { code: "MD", nom: "Moldavie" },
  { code: "MC", nom: "Monaco" },
  { code: "MN", nom: "Mongolie" },
  { code: "ME", nom: "Monténégro" },
  { code: "MS", nom: "Montserrat" },
  { code: "MZ", nom: "Mozambique" },
  { code: "NA", nom: "Namibie" },
  { code: "NR", nom: "Nauru" },
  { code: "NP", nom: "Népal" },
  { code: "NI", nom: "Nicaragua" },
  { code: "NE", nom: "Niger" },
  { code: "NG", nom: "Nigéria" },
  { code: "NU", nom: "Niue" },
  { code: "NF", nom: "Norfolk (Île)" },
  { code: "NO", nom: "Norvège" },
  { code: "NC", nom: "Nouvelle-Calédonie" },
  { code: "NZ", nom: "Nouvelle-Zélande" },
  { code: "OM", nom: "Oman" },
  { code: "UG", nom: "Ouganda" },
  { code: "UZ", nom: "Ouzbékistan" },
  { code: "PK", nom: "Pakistan" },
  { code: "PW", nom: "Palaos" },
  { code: "PS", nom: "Palestine" },
  { code: "PA", nom: "Panama" },
  { code: "PG", nom: "Papouasie-Nouvelle-Guinée" },
  { code: "PY", nom: "Paraguay" },
  { code: "NL", nom: "Pays-Bas" },
  { code: "PE", nom: "Pérou" },
  { code: "PH", nom: "Philippines" },
  { code: "PN", nom: "Pitcairn (Îles)" },
  { code: "PL", nom: "Pologne" },
  { code: "PF", nom: "Polynésie française" },
  { code: "PR", nom: "Porto Rico" },
  { code: "PT", nom: "Portugal" },
  { code: "QA", nom: "Qatar" },
  { code: "RE", nom: "Réunion" },
  { code: "DO", nom: "République dominicaine" },
  { code: "RO", nom: "Roumanie" },
  { code: "GB", nom: "Royaume-Uni" },
  { code: "RU", nom: "Russie" },
  { code: "RW", nom: "Rwanda" },
  { code: "EH", nom: "Sahara occidental" },
  { code: "BL", nom: "Saint-Barthélemy" },
  { code: "SH", nom: "Sainte-Hélène" },
  { code: "LC", nom: "Sainte-Lucie" },
  { code: "KN", nom: "Saint-Kitts-et-Nevis" },
  { code: "SM", nom: "Saint-Marin" },
  { code: "MF", nom: "Saint-Martin (partie française)" },
  { code: "SX", nom: "Saint-Martin (partie néerlandaise)" },
  { code: "PM", nom: "Saint-Pierre-et-Miquelon" },
  { code: "VC", nom: "Saint-Vincent-et-les-Grenadines" },
  { code: "SB", nom: "Salomon (Îles)" },
  { code: "SV", nom: "Salvador" },
  { code: "WS", nom: "Samoa" },
  { code: "AS", nom: "Samoa américaines" },
  { code: "ST", nom: "Sao Tomé-et-Principe" },
  { code: "SN", nom: "Sénégal" },
  { code: "RS", nom: "Serbie" },
  { code: "SC", nom: "Seychelles" },
  { code: "SL", nom: "Sierra Leone" },
  { code: "SG", nom: "Singapour" },
  { code: "SK", nom: "Slovaquie" },
  { code: "SI", nom: "Slovénie" },
  { code: "SO", nom: "Somalie" },
  { code: "SD", nom: "Soudan" },
  { code: "SS", nom: "Soudan du Sud" },
  { code: "LK", nom: "Sri Lanka" },
  { code: "SE", nom: "Suède" },
  { code: "CH", nom: "Suisse" },
  { code: "SR", nom: "Suriname" },
  { code: "SJ", nom: "Svalbard et Jan Mayen" },
  { code: "SY", nom: "Syrie" },
  { code: "TW", nom: "Taïwan" },
  { code: "TJ", nom: "Tadjikistan" },
  { code: "TZ", nom: "Tanzanie" },
  { code: "TD", nom: "Tchad" },
  { code: "CZ", nom: "Tchéquie" },
  { code: "TH", nom: "Thaïlande" },
  { code: "TL", nom: "Timor-Leste" },
  { code: "TG", nom: "Togo" },
  { code: "TK", nom: "Tokelau" },
  { code: "TO", nom: "Tonga" },
  { code: "TT", nom: "Trinité-et-Tobago" },
  { code: "TN", nom: "Tunisie" },
  { code: "TM", nom: "Turkménistan" },
  { code: "TC", nom: "Turks-et-Caïcos (Îles)" },
  { code: "TR", nom: "Turquie" },
  { code: "TV", nom: "Tuvalu" },
  { code: "UA", nom: "Ukraine" },
  { code: "UY", nom: "Uruguay" },
  { code: "US", nom: "États-Unis" },
  { code: "VU", nom: "Vanuatu" },
  { code: "VA", nom: "Vatican" },
  { code: "VE", nom: "Venezuela" },
  { code: "VN", nom: "Viêt Nam" },
  { code: "VG", nom: "Vierges britanniques (Îles)" },
  { code: "VI", nom: "Vierges américaines (Îles)" },
  { code: "WF", nom: "Wallis-et-Futuna" },
  { code: "YE", nom: "Yémen" },
  { code: "ZM", nom: "Zambie" },
  { code: "ZW", nom: "Zimbabwe" },
]

/**
 * Map code ISO → nom, pour lookup O(1)
 * Usage : PAYS_PAR_CODE["BJ"] → "Bénin"
 */
export const PAYS_PAR_CODE = Object.fromEntries(
  PAYS_LIST.map(({ code, nom }) => [code, nom])
)